# Diese Datei wird verwendet, um den pnpm-Arbeitsbereich für das Frontend-Projekt zu konfigurieren.
# Sie gibt an, welche Pakete im Arbeitsbereich enthalten sind und welche gebaut werden dürfen.
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
