# Gradle Einstellungen.
# IDE (z.B. IntelliJ IDEA) Benutzer:
# Gradle Einstellungen, die über die IDE konfiguriert werden, überschreiben *alle* Einstellungen,
# die in dieser Datei angegeben sind.
# Weitere Details zur Konfiguration Ihrer Build-Umgebung finden Sie unter
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Diese Einstellung legt die maximale Heap-Größe für die Gradle-JVM auf 2048 MB fest und stellt sicher,
# dass die Dateicodierung auf UTF-8 eingestellt ist, was wichtig für die Verarbeitung von Textdateien ist.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Verschiedene Gradle-Optionen, die die Build-Performance verbessern können
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
