# Profil Konfiguration
spring.profiles.active=local

## Server Konfiguration
server.port=8080

## H2 Console Konfiguration
spring.h2.console.enabled=true
spring.h2.console.path=/api/h2-console

## H2/DataSource Konfiguration
spring.datasource.url=jdbc:h2:mem:tmws;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

## JPA Konfiguration
spring.jpa.properties.hibernate.connection.url=${spring.datasource.url}
spring.jpa.properties.hibernate.connection.username=${JPA_USERNAME}
spring.jpa.properties.hibernate.connection.password=${JPA_PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

## Security Konfiguration
spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

## Mail Konfiguration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## JWT Konfiguration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Actuator Konfiguration
management.endpoints.web.base-path=/api
management.endpoints.web.exposure.include=health, info
management.endpoints.web.discovery.enabled=false
management.endpoints.web.cors.allowed-origins=http://localhost:4200
management.endpoints.web.cors.allowed-methods=GET
management.endpoint.health.show-components=always

## Logging
logging.level.org.springframework=INFO
logging.level.io.github.mexikoedi.tmws=DEBUG
