name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Java Build and Test Job

    # GitHub token permissions
    permissions:
      contents: read

    env:
      DATASOURCE_USERNAME: test
      DATASOURCE_PASSWORD: test
      JPA_USERNAME: test
      JPA_PASSWORD: test
      SECURITY_USERNAME: test
      SECURITY_PASSWORD: test
      MAIL_USERNAME: test
      MAIL_PASSWORD: test
      JWT_SECRET: myNotVerySecretKeyWhichIsUsedForTestingPurposesOnlyAndShouldNotBeUsedInProduction
      JWT_EXPIRATION: 40000000

    steps:
      - uses: actions/checkout@v7.0.1
      - name: Set up JDK 26
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: 26
      - name: Make gradlew executable
        working-directory: ./backend
        run: chmod +x gradlew
      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build
